require('kamachi.plugins.telescope')
require('kamachi.plugins.tokyonight')
require('kamachi.plugins.treesitter')
require('kamachi.plugins.lsp')
require('kamachi.plugins.lualine')
require('kamachi.plugins.nvim-tree')
